version: 0.2
phases:
  install:
    commands:
      - yum update -y
  pre_build:
    commands:
      - cd examples/arm64/app/
      - $(aws ecr get-login --no-include-email)
      - echo $TAG
      - IMAGE_URI="$REPOSITORY_URI:$TAG"
  build:
    commands:
      - echo Build started on `date`
      - docker build --tag $IMAGE_URI .
  post_build:
    commands:
      - docker push $IMAGE_URI
