apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: {{ .Release.Namespace }}
  labels: {{- include "containerinsights.labels" . | nindent 4 }}
data:
  cluster.name: {{ .Values.cluster.name }}
  logs.region: {{ .Values.cluster.region }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "containerinsights.fullname" . }}-metricagent-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "containerinsights.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/cloudwatch-agent.json").AsConfig | indent 2 }}

---
{{- if .Values.logAgent.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "containerinsights.fullname" . }}-logagent-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "containerinsights.labels" . | nindent 4 }}
data:
{{- with .Files.Glob "files/*.conf" }}
{{ .AsConfig | indent 2 }}
{{- end }}
{{- end }}
