{{ if .Values.halyard.additionalSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-additional-secrets
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
data:
{{- if  and .Values.halyard.additionalSecrets.create .Values.halyard.additionalSecrets.data }}
{{- range $index, $content := .Values.halyard.additionalSecrets.data }}
  {{ $index }}: |-
{{ $content | indent 4 }}
{{- end }}
{{- end }}
{{- end }}

{{- if and (or .Values.s3.accessKey .Values.s3.secretKey) (not (and .Values.s3.accessKey .Values.s3.secretKey)) -}}
{{ fail "S3: If providing credentials, accessKey and secretKey must be both set." }}
{{- end -}}

{{- if and .Values.s3.enabled .Values.s3.accessKey .Values.s3.secretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-s3
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
    component: halyard
type: Opaque
data:
  accessKey: {{ .Values.s3.accessKey | b64enc | quote }}
  secretKey: {{ .Values.s3.secretKey | b64enc | quote }}
{{- end }}

{{- if not .Values.dockerRegistryAccountSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-registry
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
    component: clouddriver
type: Opaque
data:
  {{- range $index, $account := .Values.dockerRegistries }}
  {{ $account.name }}: {{ default "" $account.password | b64enc | quote }}
  {{- end }}
{{- end }}
