apiVersion: v1
kind: Service
metadata:
  name: spin-halyard
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
    component: halyard
spec:
  ports:
  - port: 8064
    name: daemon
  clusterIP: None
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: halyard
